{
 "title": "Podinfo Dashboard",
 "tags": [ "podinfo" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(go_goroutines{app=\"podinfo\", namespace=\"app-namespace\"}, pod)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{app=\"podinfo\"}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app=\"podinfo\"}[1m])) by (method, status)",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{app=\"podinfo\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{app=\"podinfo\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app=\"podinfo\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"app-namespace\", container=~\"podinfo.*\"}[1m]) * 100",
     "legendFormat": "{{pod}} CPU"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"app-namespace\", container=~\"podinfo.*\"} / (1024 * 1024)",
     "legendFormat": "{{pod}} Memory"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "go_goroutines{app=\"podinfo\", namespace=\"app-namespace\", pod=~\"$pod.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Pause Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{app=\"podinfo\", namespace=\"app-namespace\", pod=~\"$pod.*\", quantile!=\"\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}