apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-certificate
  namespace: app-namespace
spec:
  secretName: app-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - app.local
