apiVersion: v1
kind: Service
metadata:
  name: {{ include "podinfo.name" . }}
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "podinfo.selectorLabels" . | nindent 4 }}
